name: NHL Fantasy Predictor CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Tests
      run: |
        # Add your test commands here
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: actions

    steps:
    - uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push frontend
      run: |
        cd applications/basic_server
        docker build -t registry.heroku.com/basic-server-nhl-fantasy/web . --platform linux/amd64
        docker push registry.heroku.com/basic-server-nhl-fantasy/web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    
    - name: Release frontend
      run: |
        cd applications/basic_server
        heroku container:release web -a basic-server-nhl-fantasy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: aidan.kosik@colorado.edu

    - name: Build and push collector
      run: |
        cd applications/data_collection_server
        docker build -t registry.heroku.com/collector-nhl-fantasy/web . --platform linux/amd64
        docker push registry.heroku.com/collector-nhl-fantasy/web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Release collector
      run: |
        cd applications/data_collection_server
        heroku container:release web -a collector-nhl-fantasy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: aidan.kosik@colorado.edu

